@startuml
'https://plantuml.com/class-diagram

abstract class Abstraction{
void operation();
}
class RefinedAbstraction{
public void otherOperation();
}
interface Implementor{
void operationIml();
}
class ConcreteImplementorA{
void operationIml();
}

class ConcreteImplementorB{
void operationIml();

}
Abstraction <|-- RefinedAbstraction
Implementor <|.. ConcreteImplementorA
Implementor <|.. ConcreteImplementorB
Abstraction o-right- Implementor
@enduml